/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : Principal,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Invoice {
  'id' : Principal,
  'status' : InvoiceStatus,
  'date' : Time,
  'customerId' : Principal,
  'items' : Array<InvoiceItem>,
}
export interface InvoiceItem {
  'productId' : Principal,
  'quantity' : bigint,
  'unitPrice' : number,
}
export type InvoiceStatus = { 'paid' : null } |
  { 'unpaid' : null };
export interface Product {
  'id' : Principal,
  'name' : string,
  'unit' : string,
  'stock' : bigint,
  'price' : number,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomer' : ActorMethod<[string, string, string, string], Customer>,
  'createInvoice' : ActorMethod<
    [Principal, Array<InvoiceItem>, InvoiceStatus],
    Invoice
  >,
  'createProduct' : ActorMethod<[string, string, number, bigint], Product>,
  'deleteCustomer' : ActorMethod<[Principal], undefined>,
  'deleteInvoice' : ActorMethod<[Principal], undefined>,
  'deleteProduct' : ActorMethod<[Principal], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateCustomer' : ActorMethod<
    [Principal, string, string, string, string],
    Customer
  >,
  'updateInvoice' : ActorMethod<
    [Principal, Principal, Array<InvoiceItem>, InvoiceStatus],
    Invoice
  >,
  'updateProduct' : ActorMethod<
    [Principal, string, string, number, bigint],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];