/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const InvoiceItem = IDL.Record({
  'productId' : IDL.Principal,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const Time = IDL.Int;
export const Invoice = IDL.Record({
  'id' : IDL.Principal,
  'status' : InvoiceStatus,
  'date' : Time,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(InvoiceItem),
});
export const Product = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'stock' : IDL.Nat,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
  'createInvoice' : IDL.Func(
      [IDL.Principal, IDL.Vec(InvoiceItem), InvoiceStatus],
      [Invoice],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [Product],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Principal], [], []),
  'deleteInvoice' : IDL.Func([IDL.Principal], [], []),
  'deleteProduct' : IDL.Func([IDL.Principal], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateCustomer' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
  'updateInvoice' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Vec(InvoiceItem), InvoiceStatus],
      [Invoice],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InvoiceItem = IDL.Record({
    'productId' : IDL.Principal,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const InvoiceStatus = IDL.Variant({ 'paid' : IDL.Null, 'unpaid' : IDL.Null });
  const Time = IDL.Int;
  const Invoice = IDL.Record({
    'id' : IDL.Principal,
    'status' : InvoiceStatus,
    'date' : Time,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(InvoiceItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'stock' : IDL.Nat,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Principal, IDL.Vec(InvoiceItem), InvoiceStatus],
        [Invoice],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [Product],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Principal], [], []),
    'deleteInvoice' : IDL.Func([IDL.Principal], [], []),
    'deleteProduct' : IDL.Func([IDL.Principal], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateCustomer' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
    'updateInvoice' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Vec(InvoiceItem), InvoiceStatus],
        [Invoice],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };